In [1]:
import pandas as pd
from functools import reduce

In [16]:
df=pd.read_csv("Immigration_2.csv")


df_2020=df[["Destination", "Origin","2020"]]


df_2020= df_2020.drop_duplicates(subset=["Destination", "Origin"])


df_agg_2020 = df_2020.groupby(['Origin']).agg({'2020':sum})
df_agg_2020=df_agg_2020.sort_values("2020", ascending=False)


df_2015=df[["Destination", "Origin","2015"]]

df_2015= df_2015.drop_duplicates(subset=["Destination", "Origin"])


df_agg_2015 = df_2015.groupby(['Origin']).agg({'2015':sum})
df_agg_2015=df_agg_2015.sort_values("2015", ascending=False)


df_2010=df[["Destination", "Origin","2010"]]


df_2010= df_2010.drop_duplicates(subset=["Destination", "Origin"])


df_agg_2010 = df_2010.groupby(['Origin']).agg({'2010':sum})
df_agg_2010=df_agg_2010.sort_values("2010", ascending=False)

df_2005=df[["Destination", "Origin","2005"]]

df_2005= df_2005.drop_duplicates(subset=["Destination", "Origin"])


df_agg_2005 = df_2005.groupby(['Origin']).agg({'2005':sum})
df_agg_2005=df_agg_2005.sort_values("2005", ascending=False)

df_2000=df[["Destination", "Origin","2000"]]


df_2000= df_2000.drop_duplicates(subset=["Destination", "Origin"])

df_agg_2000 = df_2000.groupby(['Origin']).agg({'2000':sum})
df_agg_2000=df_agg_2000.sort_values("2000", ascending=False)

df_1995=df[["Destination", "Origin","1995"]]

df_1995= df_1995.drop_duplicates(subset=["Destination", "Origin"])

df_agg_1995 = df_1995.groupby(['Origin']).agg({'1995':sum})
df_agg_1995=df_agg_1995.sort_values("1995", ascending=False)

df_1990=df[["Destination", "Origin","1990"]]

df_1990= df_1990.drop_duplicates(subset=["Destination", "Origin"])

df_agg_1990 = df_1990.groupby(['Origin']).agg({'1990':sum})
df_agg_1990=df_agg_1990.sort_values("1990", ascending=False)

df_final= reduce(lambda x,y: pd.merge(x,y, on='Origin'), [df_agg_1990, df_agg_1995, df_agg_2000,df_agg_2005,df_agg_2010,df_agg_2015,df_agg_2020])



df_final=df_final.sort_values("2020", ascending=False)
df_final.head(60)

,1990,1995,2000,2005,2010,2015,2020
Origin,,,,,,,
India,6612932,7144295,7912823,9567871,13188762,15852725,17841249
Mexico,4395277,6949190,9562758,10817652,12414992,11922938,11185394
Russian Federation,12653132,11587969,10664855,10302078,10118071,10179214,10755333
China,4230637,5036184,5896047,7340551,8713910,10242627,10464129
Syrian Arab Republic,620181,661220,707036,813313,1057247,6447750,8457103
Bangladesh,5449776,5423912,5442100,5493007,6309428,6810053,7387967
Pakistan,3340857,3339070,3403709,3773952,4779911,5780674,6316942
Philippines,2052867,2528351,3114186,3736265,4739453,5543348,6141098
Ukraine,5543695,5604645,5594918,5564277,5426812,5793598,6134556
Afghanistan,7679523,4347013,4750647,4116687,5269443,5400820,5853727
Venezuela (Bolivarian Republic of),185196,241680,317627,436921,560287,708830,5414978
Poland,1671804,1773277,2043485,2879210,3708409,4066805,4813196
United Kingdom,3675424,3606200,3736706,3982324,4319367,4320522,4667754
Indonesia,1630095,1944834,2422406,2791663,3429516,4078384,4614574
Kazakhstan,2971634,3295157,3554484,3717649,3797527,3885576,4203899
State of Palestine,1812576,2274529,2767290,3258049,3539831,3773889,4022677
Romania,811080,976101,1138145,2105012,3362060,3419036,3985145
Germany,2896061,3020846,3212185,3412558,3675170,3617732,3840067
Myanmar,685097,911314,1224219,1736471,2492101,2842271,3711493
Egypt,1321145,1490865,1706412,1805433,2582972,3146314,3604936
Turkey,2512158,2771188,2846869,2576690,2708031,3072370,3410055
Viet Nam,1506284,1843255,2159676,2377401,2631929,2910473,3393033
Morocco,1747758,1884114,2077554,2471130,2861010,2971845,3262213
Italy,3340700,3199304,3058260,2686672,2541453,2639424,3231794
Colombia,1009030,1215808,1433691,1883576,2553543,2698073,3023559
United States of America,1753522,1853501,2001594,2316772,2690489,2739386,3017939
South Sudan,628352,575350,461370,286105,407081,1069274,2669077
Nepal,748084,856142,977582,1289780,1712736,2270161,2599675
Sudan,629834,835099,959298,1563269,1551145,2185507,2499895
France,1285938,1431469,1640520,1807049,2047749,2223925,2451886
Republic of Korea,1518003,1699048,1880101,1979001,2255918,2155634,2207557
Iraq,642791,752516,828346,1340508,2554797,1675443,2077779
Portugal,1858690,1911152,1982693,1725347,1917504,1969150,2076385
Democratic Republic of the Congo,524576,702406,1086195,1399120,1575561,1762607,2060151
Uzbekistan,1427980,1515731,1575965,1730224,1888942,1976024,2027823
Algeria,922469,980711,1039240,1600924,1656457,1837406,2023210
Somalia,844822,966082,999826,1050629,1566139,1931555,1975730
Sri Lanka,882839,923050,978767,1151101,1453793,1655349,1959051
Brazil,490380,729531,939225,1192953,1493043,1501186,1893593
Malaysia,559712,860903,1200966,1379012,1598523,1780281,1859124
Puerto Rico,1201362,1406946,1601664,1643488,1736751,1720678,1855623
Nigeria,558125,638438,723596,925689,1072879,1420835,1841339
Haiti,524711,661354,802218,967894,1123190,1467042,1769671
Cuba,835022,933942,1047410,1159631,1313909,1504773,1755985
Bosnia and Herzegovina,861613,1372435,1496612,1500924,1572762,1593220,1687396
Bulgaria,609124,647037,687029,905647,1103319,1175544,1678336
Dominican Republic,458021,667015,889451,1014070,1184417,1454602,1608567
Burkina Faso,1023492,1218556,1283030,1356232,1439095,1524954,1606371
El Salvador,1241849,933103,949042,1118793,1337085,1512895,1599058
Central African Republic,64919,69741,81074,224095,451297,1331103,1576945
Peru,313010,505350,694058,968890,1298932,1409989,1519392
Spain,1439006,1362548,1290744,1114659,1087148,1269227,1489784
Belarus,1767487,1736400,1685545,1581028,1464510,1469635,1483340
Mali,669406,853221,818658,945707,1063217,1321240,1402388
Guatemala,348099,461835,582758,736665,924826,1118023,1368325
Iran (Islamic Republic of),630516,746315,830910,889113,985156,1155259,1324622
Yemen,455409,486198,529361,628824,876318,1095157,1301070
Lao People's Democratic Republic,483490,548363,649952,897708,1199606,1288739,1296642
Canada,991974,1062797,1141103,1182998,1264403,1258646,1286533
Albania,180126,501003,824373,965942,1117809,1142676,1250256

In [17]:
df_2020=df[["Destination", "Origin","2020"]]


df_2020= df_2020.drop_duplicates(subset=["Destination", "Origin"])


df_agg_2020 = df_2020.groupby(['Destination']).agg({'2020':sum})
df_agg_2020=df_agg_2020.sort_values("2020", ascending=False)


df_2015=df[["Destination", "Origin","2015"]]

df_2015= df_2015.drop_duplicates(subset=["Destination", "Origin"])


df_agg_2015 = df_2015.groupby(['Destination']).agg({'2015':sum})
df_agg_2015=df_agg_2015.sort_values("2015", ascending=False)


df_2010=df[["Destination", "Origin","2010"]]


df_2010= df_2010.drop_duplicates(subset=["Destination", "Origin"])


df_agg_2010 = df_2010.groupby(['Destination']).agg({'2010':sum})
df_agg_2010=df_agg_2010.sort_values("2010", ascending=False)

df_2005=df[["Destination", "Origin","2005"]]

df_2005= df_2005.drop_duplicates(subset=["Destination", "Origin"])


df_agg_2005 = df_2005.groupby(['Destination']).agg({'2005':sum})
df_agg_2005=df_agg_2005.sort_values("2005", ascending=False)

df_2000=df[["Destination", "Origin","2000"]]


df_2000= df_2000.drop_duplicates(subset=["Destination", "Origin"])

df_agg_2000 = df_2000.groupby(['Destination']).agg({'2000':sum})
df_agg_2000=df_agg_2000.sort_values("2000", ascending=False)

df_1995=df[["Destination", "Origin","1995"]]

df_1995= df_1995.drop_duplicates(subset=["Destination", "Origin"])

df_agg_1995 = df_1995.groupby(['Destination']).agg({'1995':sum})
df_agg_1995=df_agg_1995.sort_values("1995", ascending=False)

df_1990=df[["Destination", "Origin","1990"]]

df_1990= df_1990.drop_duplicates(subset=["Destination", "Origin"])

df_agg_1990 = df_1990.groupby(['Destination']).agg({'1990':sum})
df_agg_1990=df_agg_1990.sort_values("1990", ascending=False)

df_final= reduce(lambda x,y: pd.merge(x,y, on='Destination'), [df_agg_1990, df_agg_1995, df_agg_2000,df_agg_2005,df_agg_2010,df_agg_2015,df_agg_2020])



df_final=df_final.sort_values("2020", ascending=False)
df_final.head(50)

,1990,1995,2000,2005,2010,2015,2020
Destination,,,,,,,
United States of America,20141921,26604854,33172751,37005562,42074589,45774971,46598723
Germany,5926839,7412794,8931737,9216552,9697052,10105615,15608391
Saudi Arabia,4830679,4950773,5086745,6283624,8147064,10408329,13001347
Russian Federation,11517183,11921092,11892610,11663653,11194534,11643055,11636554
United Kingdom,3575525,4034204,4560937,5734529,6864266,8177323,9082536
France,5895386,6086052,6276716,6734252,7306098,7872952,8518941
United Arab Emirates,1287556,1781444,2378173,3183249,7094266,7752055,8451322
Canada,4319804,4847779,5491026,6056674,6735855,7405913,8024473
Australia,3946012,4130952,4333550,4800509,5769570,6591860,7532833
Spain,816864,1011626,1645940,4101348,6275801,5873416,6819451
Italy,1427857,1774215,2120571,3951503,5781507,5799648,6379694
Turkey,979633,1071375,1175461,1214989,1261121,4197009,5912738
India,7365037,6918237,6373046,5780415,5327507,4981127,4664165
Ukraine,6481438,5774245,5137559,4694360,4479641,4495836,4571036
Thailand,528671,809682,1257759,2195218,3233630,3469395,3631614
Kazakhstan,3192260,2936413,2680568,2885521,3090475,3287097,3459530
Jordan,1144310,1534834,1925359,2196432,2781508,3150117,3435756
Malaysia,609304,843822,1337233,1763735,2242623,3061157,3247513
Pakistan,6203799,3665602,4178579,3171399,3940511,3425927,3201265
Middle Africa,1281136,2463906,1538179,1740923,1925496,2654728,3023044
Kuwait,1048104,893634,1086284,1267972,1768516,2751639,2985881
"China, Hong Kong SAR",2000265,2152873,2305464,2524034,2748711,2809169,2929168
Iran (Islamic Republic of),4282607,2928766,2458733,2529688,2704744,2716186,2785736
Japan,1065385,1340239,1648768,1945860,2064499,2076531,2490217
Côte d'Ivoire,1794958,2038795,2103321,2201917,2300514,2401128,2490044
Switzerland,1197055,1307968,1462792,1690569,1932845,2172891,2387258
Oman,299352,521084,596366,638222,783100,1780894,2276522
Singapore,445694,793855,1218865,1526620,1919435,2201935,2237618
Argentina,1565150,1512303,1459485,1614750,1767580,2042036,2237042
Qatar,305265,353830,349667,624746,1406620,1654997,2192930
Netherlands,1118486,1270730,1466752,1631884,1722200,1796332,2136727
Sweden,719491,853829,915113,1033028,1246140,1517711,1915164
Colombia,93339,96910,100468,98561,120955,148532,1893004
Belgium,1251696,1232867,1173171,1191833,1414183,1672385,1888034
Bangladesh,741548,800479,859424,892782,1100737,1138134,1790721
Austria,791774,893239,994703,1125111,1272619,1480923,1735447
Uganda,524217,588222,581763,590870,490451,848659,1717975
Lebanon,520116,604819,689524,739656,791350,1914698,1711373
Republic of Korea,41151,118117,232929,463215,876550,1351254,1667497
Chile,89313,122144,154883,239371,323764,561576,1602394
New Zealand,590487,640651,732305,891247,1001965,1096685,1422904
Israel,1481131,1544827,1522017,1428322,1351951,1394306,1353916
Sudan,1369612,1019543,770450,509151,590487,598718,1348983
Greece,617164,854735,1106363,1184904,1314609,1236752,1334135
Venezuela (Bolivarian Republic of),1024656,1018605,1013447,1076250,1347101,1404185,1323848
Peru,55705,55789,65246,76670,103333,152662,1219806
Nigeria,299556,361537,437977,870507,889165,1076442,1177115
Mexico,693667,456565,536002,710402,966922,992415,1174191
Uzbekistan,1577433,1433906,1325101,1247571,1140101,1094008,1085715
Belarus,1248782,1186020,1123275,1106673,1090088,1082594,1066786